name: notus_format
description: Platform-agnostic rich text document model based on Delta format and used in Zefyrka editor.
version: 1.0.2
homepage: https://github.com/glynskyi/notus_format

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  collection: ^1.15.0
  quill_format: ^1.0.2

dev_dependencies:
  pedantic: ^1.11.0
  test: ^1.17.8
  coverage: ^1.0.2